### ISSUE TITLE
Get rid of the closures

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/event#304]
When the traits were designed Rust did not have `if let` expressions, so now it should be possible to make it nicer. All the events currently are lightweight, so using `Copy/Clone` is acceptable. In the case for text input I think an allocation is OK, considering this does not happen frequently.

- [x] `FocusEvent: fn focus_args() -> Option<bool>`
- [x] `MouseCursorEvent: fn mouse_cursor_args() -> Option<[f64, ..2]>`
- [x] `MouseRelativeEvent: fn mouse_relative_args() -> Option<[f64, ..2]>`
- [x] `MouseScrollEvent: fn mouse_scroll_args() -> Option<[f64, ..2]>`
- [x] `PressEvent: fn press_args() -> Option<Button>`
- [x] `ReleaseEvent: fn release_args() -> Option<Button>`
- [x] `RenderEvent: fn render_args() -> Option<RenderArgs>`
- [x] `ResizeEvent: fn resize_args() -> Option<[u32, ..2]>`
- [x] `TextEvent: fn text_args() -> Option<String>`
- [x] `UpdateEvent: fn update_args() -> Option<UpdateArgs>`

Progress

- [x] Add suffix `_args` for new methods
- [ ] Translate some code to test

**Comment by mitchmindtree** [comment]
:+1:

**Comment by bvssvni** [comment]
I'd like to add them with a suffix `_args` first to check how stuff works out. No need to break everything if we don't have to...

**Comment by bvssvni** [comment]
The closure syntax is nice for single-liners, but the `if let` syntax is nicer for multiple lines, or when you want to pattern match a mouse button or something.

I'd say we'll keep both.
