### ISSUE TITLE
gfx need call `device.after_frame()` after swap buffers.

### ISSUE THREAD

**Issue by Potpourri** [PistonDevelopers/event#335]
Perhaps need add new event callable after `window.swap_buffers()`?

**Comment by bvssvni** [comment]
Name suggestions?

**Comment by Potpourri** [comment]
Maybe `Cleanup`? This is what make `after_frame`, cleanup frame handles on resources.

**Comment by bvssvni** [comment]
What about `AfterRender`?

**Comment by Potpourri** [comment]
`AfterRender` was my first variant, if you like then I agree.

**Comment by bvssvni** [comment]
What will happen if a window does triple buffering? Should we figure out this before adding the new event?

**Comment by Potpourri** [comment]
Why do you think that this could be a problem?

**Comment by bvssvni** [comment]
I was wondering whether objects could be submitted for drawing when released. With double buffering, the rendering must be done when swapping frames, but with triple buffering, there could be object submitted for drawing to the second frame buffer.

**Comment by Potpourri** [comment]
I think this isn't possible. With triple buffering we have two back buffer, but they are used alternately. Back buffer automatically switches when swapping frames. We can't control this process and it isn't much different from double buffering.

**Comment by bvssvni** [comment]
I opened https://github.com/PistonDevelopers/event/issues/336
